name: utility
description: this project is utility project for using melos package
publish_to: 'none' 

version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  
  # 일부 프로젝트 사용 
  auto_size_text: ^3.0.0 
  carousel_slider: ^5.0.0
  oktoast: ^3.4.0 # 해당 패키지도 전 프로젝트 사용하나 대중적인것으로 변경 고민
  device_info_plus: ^11.2.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  widget_zoom: ^0.0.4
  flutter_widget_from_html: ^0.17.0
  http: ^1.4.0
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.2.0
  html: ^0.15.6

  # 전 프로젝트 필수 사용 패키지 
  loading_animation_widget: ^1.3.0
  table_calendar: ^3.1.2
  get: ^4.6.6
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_local_notifications: ^19.4.0
  package_info_plus: ^8.3.0 # 자동 업데이트 관련 패키지 
  intl: ^0.20.2

  # 데이터 디바이스 저장 패키지
  flutter_secure_storage: ^9.2.2 # 해당 패키지는 일부 프로젝트만 사용중
  shared_preferences: ^2.3.3

  # firebase 필수 패키지
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_remote_config: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_auth: ^6.1.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
